-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity scal is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    n : IN STD_LOGIC_VECTOR (1 downto 0);
    a : IN STD_LOGIC_VECTOR (31 downto 0);
    x_offset : IN STD_LOGIC_VECTOR (63 downto 0);
    G_0_i : IN STD_LOGIC_VECTOR (31 downto 0);
    G_0_o : OUT STD_LOGIC_VECTOR (31 downto 0);
    G_0_o_ap_vld : OUT STD_LOGIC;
    G_1_i : IN STD_LOGIC_VECTOR (31 downto 0);
    G_1_o : OUT STD_LOGIC_VECTOR (31 downto 0);
    G_1_o_ap_vld : OUT STD_LOGIC;
    G_2_i : IN STD_LOGIC_VECTOR (31 downto 0);
    G_2_o : OUT STD_LOGIC_VECTOR (31 downto 0);
    G_2_o_ap_vld : OUT STD_LOGIC;
    G_3_i : IN STD_LOGIC_VECTOR (31 downto 0);
    G_3_o : OUT STD_LOGIC_VECTOR (31 downto 0);
    G_3_o_ap_vld : OUT STD_LOGIC;
    G_4_i : IN STD_LOGIC_VECTOR (31 downto 0);
    G_4_o : OUT STD_LOGIC_VECTOR (31 downto 0);
    G_4_o_ap_vld : OUT STD_LOGIC;
    G_5_i : IN STD_LOGIC_VECTOR (31 downto 0);
    G_5_o : OUT STD_LOGIC_VECTOR (31 downto 0);
    G_5_o_ap_vld : OUT STD_LOGIC;
    G_6_i : IN STD_LOGIC_VECTOR (31 downto 0);
    G_6_o : OUT STD_LOGIC_VECTOR (31 downto 0);
    G_6_o_ap_vld : OUT STD_LOGIC;
    G_7_i : IN STD_LOGIC_VECTOR (31 downto 0);
    G_7_o : OUT STD_LOGIC_VECTOR (31 downto 0);
    G_7_o_ap_vld : OUT STD_LOGIC;
    G_8_i : IN STD_LOGIC_VECTOR (31 downto 0);
    G_8_o : OUT STD_LOGIC_VECTOR (31 downto 0);
    G_8_o_ap_vld : OUT STD_LOGIC );
end;


architecture behav of scal is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal trunc_ln27_fu_91_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln27_reg_239 : STD_LOGIC_VECTOR (3 downto 0);
    signal i_fu_100_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal i_reg_247 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal add_ln27_fu_110_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln27_reg_252 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln25_fu_95_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_151_p11 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal i_0_reg_76 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal grp_fu_87_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln27_fu_106_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);

    component DLU_fmul_32ns_32ncud IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component DLU_mux_94_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        din5_WIDTH : INTEGER;
        din6_WIDTH : INTEGER;
        din7_WIDTH : INTEGER;
        din8_WIDTH : INTEGER;
        din9_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        din4 : IN STD_LOGIC_VECTOR (31 downto 0);
        din5 : IN STD_LOGIC_VECTOR (31 downto 0);
        din6 : IN STD_LOGIC_VECTOR (31 downto 0);
        din7 : IN STD_LOGIC_VECTOR (31 downto 0);
        din8 : IN STD_LOGIC_VECTOR (31 downto 0);
        din9 : IN STD_LOGIC_VECTOR (3 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    DLU_fmul_32ns_32ncud_U54 : component DLU_fmul_32ns_32ncud
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => tmp_fu_151_p11,
        din1 => a,
        ce => ap_const_logic_1,
        dout => grp_fu_87_p2);

    DLU_mux_94_32_1_1_U55 : component DLU_mux_94_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 32,
        din5_WIDTH => 32,
        din6_WIDTH => 32,
        din7_WIDTH => 32,
        din8_WIDTH => 32,
        din9_WIDTH => 4,
        dout_WIDTH => 32)
    port map (
        din0 => G_0_i,
        din1 => G_1_i,
        din2 => G_2_i,
        din3 => G_3_i,
        din4 => G_4_i,
        din5 => G_5_i,
        din6 => G_6_i,
        din7 => G_7_i,
        din8 => G_8_i,
        din9 => add_ln27_reg_252,
        dout => tmp_fu_151_p11);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    i_0_reg_76_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                i_0_reg_76 <= i_reg_247;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                i_0_reg_76 <= ap_const_lv2_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln25_fu_95_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                add_ln27_reg_252 <= add_ln27_fu_110_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                i_reg_247 <= i_fu_100_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                trunc_ln27_reg_239 <= trunc_ln27_fu_91_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln25_fu_95_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln25_fu_95_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;

    G_0_o_assign_proc : process(G_0_i, add_ln27_reg_252, ap_CS_fsm_state6, grp_fu_87_p2)
    begin
        if (((ap_const_lv4_0 = add_ln27_reg_252) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            G_0_o <= grp_fu_87_p2;
        else 
            G_0_o <= G_0_i;
        end if; 
    end process;


    G_0_o_ap_vld_assign_proc : process(add_ln27_reg_252, ap_CS_fsm_state6)
    begin
        if (((ap_const_lv4_0 = add_ln27_reg_252) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            G_0_o_ap_vld <= ap_const_logic_1;
        else 
            G_0_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    G_1_o_assign_proc : process(G_1_i, add_ln27_reg_252, ap_CS_fsm_state6, grp_fu_87_p2)
    begin
        if (((ap_const_lv4_1 = add_ln27_reg_252) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            G_1_o <= grp_fu_87_p2;
        else 
            G_1_o <= G_1_i;
        end if; 
    end process;


    G_1_o_ap_vld_assign_proc : process(add_ln27_reg_252, ap_CS_fsm_state6)
    begin
        if (((ap_const_lv4_1 = add_ln27_reg_252) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            G_1_o_ap_vld <= ap_const_logic_1;
        else 
            G_1_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    G_2_o_assign_proc : process(G_2_i, add_ln27_reg_252, ap_CS_fsm_state6, grp_fu_87_p2)
    begin
        if (((ap_const_lv4_2 = add_ln27_reg_252) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            G_2_o <= grp_fu_87_p2;
        else 
            G_2_o <= G_2_i;
        end if; 
    end process;


    G_2_o_ap_vld_assign_proc : process(add_ln27_reg_252, ap_CS_fsm_state6)
    begin
        if (((ap_const_lv4_2 = add_ln27_reg_252) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            G_2_o_ap_vld <= ap_const_logic_1;
        else 
            G_2_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    G_3_o_assign_proc : process(G_3_i, add_ln27_reg_252, ap_CS_fsm_state6, grp_fu_87_p2)
    begin
        if (((ap_const_lv4_3 = add_ln27_reg_252) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            G_3_o <= grp_fu_87_p2;
        else 
            G_3_o <= G_3_i;
        end if; 
    end process;


    G_3_o_ap_vld_assign_proc : process(add_ln27_reg_252, ap_CS_fsm_state6)
    begin
        if (((ap_const_lv4_3 = add_ln27_reg_252) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            G_3_o_ap_vld <= ap_const_logic_1;
        else 
            G_3_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    G_4_o_assign_proc : process(G_4_i, add_ln27_reg_252, ap_CS_fsm_state6, grp_fu_87_p2)
    begin
        if (((ap_const_lv4_4 = add_ln27_reg_252) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            G_4_o <= grp_fu_87_p2;
        else 
            G_4_o <= G_4_i;
        end if; 
    end process;


    G_4_o_ap_vld_assign_proc : process(add_ln27_reg_252, ap_CS_fsm_state6)
    begin
        if (((ap_const_lv4_4 = add_ln27_reg_252) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            G_4_o_ap_vld <= ap_const_logic_1;
        else 
            G_4_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    G_5_o_assign_proc : process(G_5_i, add_ln27_reg_252, ap_CS_fsm_state6, grp_fu_87_p2)
    begin
        if (((ap_const_lv4_5 = add_ln27_reg_252) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            G_5_o <= grp_fu_87_p2;
        else 
            G_5_o <= G_5_i;
        end if; 
    end process;


    G_5_o_ap_vld_assign_proc : process(add_ln27_reg_252, ap_CS_fsm_state6)
    begin
        if (((ap_const_lv4_5 = add_ln27_reg_252) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            G_5_o_ap_vld <= ap_const_logic_1;
        else 
            G_5_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    G_6_o_assign_proc : process(G_6_i, add_ln27_reg_252, ap_CS_fsm_state6, grp_fu_87_p2)
    begin
        if (((ap_const_lv4_6 = add_ln27_reg_252) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            G_6_o <= grp_fu_87_p2;
        else 
            G_6_o <= G_6_i;
        end if; 
    end process;


    G_6_o_ap_vld_assign_proc : process(add_ln27_reg_252, ap_CS_fsm_state6)
    begin
        if (((ap_const_lv4_6 = add_ln27_reg_252) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            G_6_o_ap_vld <= ap_const_logic_1;
        else 
            G_6_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    G_7_o_assign_proc : process(G_7_i, add_ln27_reg_252, ap_CS_fsm_state6, grp_fu_87_p2)
    begin
        if (((ap_const_lv4_7 = add_ln27_reg_252) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            G_7_o <= grp_fu_87_p2;
        else 
            G_7_o <= G_7_i;
        end if; 
    end process;


    G_7_o_ap_vld_assign_proc : process(add_ln27_reg_252, ap_CS_fsm_state6)
    begin
        if (((ap_const_lv4_7 = add_ln27_reg_252) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            G_7_o_ap_vld <= ap_const_logic_1;
        else 
            G_7_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    G_8_o_assign_proc : process(G_8_i, add_ln27_reg_252, ap_CS_fsm_state6, grp_fu_87_p2)
    begin
        if ((not((ap_const_lv4_0 = add_ln27_reg_252)) and not((ap_const_lv4_1 = add_ln27_reg_252)) and not((ap_const_lv4_2 = add_ln27_reg_252)) and not((ap_const_lv4_3 = add_ln27_reg_252)) and not((ap_const_lv4_4 = add_ln27_reg_252)) and not((ap_const_lv4_5 = add_ln27_reg_252)) and not((ap_const_lv4_6 = add_ln27_reg_252)) and not((ap_const_lv4_7 = add_ln27_reg_252)) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            G_8_o <= grp_fu_87_p2;
        else 
            G_8_o <= G_8_i;
        end if; 
    end process;


    G_8_o_ap_vld_assign_proc : process(add_ln27_reg_252, ap_CS_fsm_state6)
    begin
        if ((not((ap_const_lv4_0 = add_ln27_reg_252)) and not((ap_const_lv4_1 = add_ln27_reg_252)) and not((ap_const_lv4_2 = add_ln27_reg_252)) and not((ap_const_lv4_3 = add_ln27_reg_252)) and not((ap_const_lv4_4 = add_ln27_reg_252)) and not((ap_const_lv4_5 = add_ln27_reg_252)) and not((ap_const_lv4_6 = add_ln27_reg_252)) and not((ap_const_lv4_7 = add_ln27_reg_252)) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            G_8_o_ap_vld <= ap_const_logic_1;
        else 
            G_8_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_ln27_fu_110_p2 <= std_logic_vector(unsigned(zext_ln27_fu_106_p1) + unsigned(trunc_ln27_reg_239));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln25_fu_95_p2)
    begin
        if ((((icmp_ln25_fu_95_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln25_fu_95_p2)
    begin
        if (((icmp_ln25_fu_95_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    i_fu_100_p2 <= std_logic_vector(unsigned(i_0_reg_76) + unsigned(ap_const_lv2_1));
    icmp_ln25_fu_95_p2 <= "1" when (i_0_reg_76 = n) else "0";
    trunc_ln27_fu_91_p1 <= x_offset(4 - 1 downto 0);
    zext_ln27_fu_106_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_0_reg_76),4));
end behav;
